# font2txf Makefile Configuration

# You generally shouldn't change this unless you are making forked
# versions (or test versions)
# Version numbers must be of the form x.y.z
VERSION = 1.12.0

# Host compiler and flags
HOSTCXX     = g++
HOSTSTRIP   = strip

# Enable this to activate debug build
#DEBUG = 1

# Enable this to enable the preview option
# Preview option will display the txf file after conversion
# This requires Freeglut
#PREVIEW = 1

# Directory where to install font2txf in
TOOLINSTALLDIR	= ..

# Define this if you want a standalone, statically linked, no dependency binary
# This make sense on Windows, but not sure for the other platforms, probably not
#STANDALONE_BINARY = 1

# This is on by default for Windows (MinGW/MSYS, MinGW-w64/MSYS2 and Cygwin)
ifdef WINDOWS
  STANDALONE_BINARY = 1
endif

# If you need to pass some specific args you can use the standard variables
#CCFLAGS = -D_DEBUG_FONT_DUMP_TO_CONSOLE
#LDFLAGS =
#LDLIBS =

# For MinGW/MSYS, MinGW-w64/MSYS2 and Cygwin
ifdef WINDOWS
  HOSTCFLAGS += -D_WIN32
  EXECUTABLEEXTENSION = .exe
endif

# For DreamSDK, we can enable the preview feature by default
ifdef DREAMSDK
  PREVIEW = 1
endif
