# KallistiOS ##version##
#
# examples/dreamcast/filesystem/Makefile
# Copyright (C) 2024 Andress Barajas
#

all:
	$(KOS_MAKE) -C pty
	$(KOS_MAKE) -C browse
	$(KOS_MAKE) -C sd

clean:
	$(KOS_MAKE) -C pty clean
	$(KOS_MAKE) -C browse clean
	$(KOS_MAKE) -C sd clean

dist:
	$(KOS_MAKE) -C pty dist
	$(KOS_MAKE) -C browse dist
	$(KOS_MAKE) -C sd dist


