# KallistiOS ##version##
#
# examples/dreamcast/filesystem/Makefile
# Copyright (C) 2024 Andress Barajas
#

all:
	$(KOS_MAKE) -C pty

clean:
	$(KOS_MAKE) -C pty clean

dist:
	$(KOS_MAKE) -C pty dist


